# docker-compose up -d
# docker logs -f spring_app
# docker ps
services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    #  MYSQL_DATABASE: test_db
      MYSQL_DATABASE: recursos_tic_testing
      MYSQL_USER: tic_user
      MYSQL_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
    #ports:
    #  - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring_app:
    image: spring-thymeleaf:1.0.0
    container_name: spring_app
    environment:
    #  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db
    #  SPRING_DATASOURCE_USERNAME: root
    #  SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recursos_tic_testing
      SPRING_DATASOURCE_USERNAME: tic_user
      SPRING_DATASOURCE_PASSWORD: example
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql_data: