# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Clean
        run: mvn clean

      - name: Unit Testing
        run: mvn test

      - name: Integration Testing
        run: mvn verify -D maven.test.failure.ignore=true

      - name: Site
        run: mvn site

      - name: Análisis con SonarCloud
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kevinzamoraa_recursos_tic-grupo1-java_testing-24

      # TODO kevin, crear proyecto en SonarCloud y obtener token y añadirlo en GitHub repository secrets
      #      - name: Análisis con SonarCloud
      #        env:
      #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kevinzamoraa_recursos_tic-grupo1-java_testing-24 -Dsonar.organization=kevinzamoraa -Dsonar.host.url=https://sonarcloud.io